"""All station type definitions with inputs, outputs, costs, and operating parameters."""

from backend.simulation.distributions import (
    NormalDistribution, LogNormalDistribution, FixedRateDistribution,
)

# Station definitions keyed by station_type
STATION_DEFINITIONS = {
    "easy_frame_saw": {
        "display_name": "EasyFrame Saw",
        "input_types": ["raw_lumber"],
        "output_types": ["cut_lumber"],
        "cycle_time": FixedRateDistribution(units_per_hour=20),
        "crew_size": 2,
        "capex_cost": 150_000,
        "install_cost": 10_000,
        "monthly_maintenance": 500,
        "footprint": (10, 40),
        "default_position": (80, 60),
        "required_resources": [],
        "breakdown_mtbf_hours": 200,
        "repair_hours": 4,
    },
    "hundegger_saw": {
        "display_name": "Hundegger SC3",
        "input_types": ["raw_lumber"],
        "output_types": ["cut_lumber"],
        "cycle_time": FixedRateDistribution(units_per_hour=30),
        "crew_size": 2,
        "capex_cost": 800_000,
        "install_cost": 50_000,
        "monthly_maintenance": 2_000,
        "footprint": (10, 60),
        "default_position": (80, 60),
        "required_resources": [],
        "breakdown_mtbf_hours": 300,
        "repair_hours": 6,
    },
    "onsrud_cnc": {
        "display_name": "Onsrud CNC Router",
        "input_types": ["raw_sheet_goods"],
        "output_types": ["cut_sheets"],
        "cycle_time": FixedRateDistribution(units_per_hour=8),
        "crew_size": 1,
        "capex_cost": 250_000,
        "install_cost": 20_000,
        "monthly_maintenance": 1_000,
        "footprint": (15, 30),
        "default_position": (160, 60),
        "required_resources": [],
        "breakdown_mtbf_hours": 300,
        "repair_hours": 6,
    },
    "manual_framing_table": {
        "display_name": "Manual Framing Table",
        "input_types": ["cut_lumber", "cut_sheets"],
        "output_types": ["Panel"],
        "cycle_time": LogNormalDistribution(mean=82, std=18, min_val=45, max_val=180),
        "crew_size": 3,
        "capex_cost": 15_000,
        "install_cost": 2_000,
        "monthly_maintenance": 200,
        "footprint": (20, 60),
        "default_position": (120, 120),
        "required_resources": [],
        "breakdown_mtbf_hours": 0,  # no breakdown
        "repair_hours": 0,
    },
    "acadia_workcell": {
        "display_name": "Acadia Workcell",
        "input_types": ["cut_lumber", "cut_sheets"],
        "output_types": ["Panel"],
        "cycle_time": NormalDistribution(mean=60, std=10),
        "crew_size": 2,
        "capex_cost": 500_000,
        "install_cost": 50_000,
        "monthly_maintenance": 2_000,
        "footprint": (25, 65),
        "default_position": (250, 120),
        "required_resources": [],
        "breakdown_mtbf_hours": 0,
        "repair_hours": 0,
    },
    "floor_cassette_bay": {
        "display_name": "Floor Cassette Bay",
        "input_types": ["lvl_beams", "tji_joists", "cut_sheets"],
        "output_types": ["FloorCassette"],
        "cycle_time": NormalDistribution(mean=480, std=60),
        "crew_size": 4,
        "capex_cost": 50_000,
        "install_cost": 10_000,
        "monthly_maintenance": 500,
        "footprint": (20, 60),
        "default_position": (60, 180),
        "required_resources": [("gantry_crane_module_matrix", 1)],
        "breakdown_mtbf_hours": 0,
        "repair_hours": 0,
    },
    "integration_bay": {
        "display_name": "Integration Bay",
        "input_types": ["FloorCassette", "Panel"],
        "output_types": ["IntegratedModule"],
        "cycle_time": NormalDistribution(mean=960, std=120),
        "crew_size": 5,
        "capex_cost": 60_000,
        "install_cost": 15_000,
        "monthly_maintenance": 500,
        "footprint": (20, 60),
        "default_position": (120, 200),
        "required_resources": [("gantry_crane_module_matrix", 2)],
        "breakdown_mtbf_hours": 0,
        "repair_hours": 0,
    },
    "finishing_bay": {
        "display_name": "Finishing Bay",
        "input_types": ["IntegratedModule"],
        "output_types": ["FinishedModule"],
        "cycle_time": NormalDistribution(mean=4320, std=480),
        "crew_size": 3,
        "capex_cost": 10_000,
        "install_cost": 2_000,
        "monthly_maintenance": 200,
        "footprint": (20, 60),
        "default_position": (60, 250),
        "required_resources": [],
        "breakdown_mtbf_hours": 0,
        "repair_hours": 0,
    },
    "kitting_area": {
        "display_name": "Kitting Area",
        "input_types": ["mep_rough_materials", "trim_materials"],
        "output_types": ["mep_rough_materials", "trim_materials"],  # kits pass through
        "cycle_time": NormalDistribution(mean=60, std=10),
        "crew_size": 2,
        "capex_cost": 20_000,
        "install_cost": 5_000,
        "monthly_maintenance": 200,
        "footprint": (30, 30),
        "default_position": (300, 60),
        "required_resources": [],
        "breakdown_mtbf_hours": 0,
        "repair_hours": 0,
    },
    "module_exit": {
        "display_name": "Module Exit",
        "input_types": ["FinishedModule"],
        "output_types": [],
        "cycle_time": NormalDistribution(mean=30, std=5),
        "crew_size": 2,
        "capex_cost": 0,
        "install_cost": 0,
        "monthly_maintenance": 0,
        "footprint": (20, 60),
        "default_position": (200, 275),
        "required_resources": [("tugger", 1), ("field_lift_pro", 1)],
        "breakdown_mtbf_hours": 0,
        "repair_hours": 0,
    },
}

# Default resource counts per ramp phase
DEFAULT_RESOURCES = {
    "day_1": {
        "gantry_crane_module_matrix": 2,
        "forklift": 1,
        "tugger": 1,
        "panel_cart": 4,
        "field_lift_pro": 2,
        "scissor_lift": 2,
        "wav": 1,
        "material_cart": 10,
    },
    "day_90": {
        "gantry_crane_module_matrix": 4,
        "forklift": 2,
        "tugger": 1,
        "panel_cart": 6,
        "field_lift_pro": 3,
        "scissor_lift": 3,
        "wav": 1,
        "material_cart": 15,
    },
    "day_180": {
        "gantry_crane_module_matrix": 6,
        "forklift": 2,
        "tugger": 1,
        "panel_cart": 8,
        "field_lift_pro": 4,
        "scissor_lift": 4,
        "wav": 2,
        "material_cart": 20,
    },
}
